#ifndef __ERROR_H__
#define __ERROR_H__

typedef int error_t;

#define OK 0
#define ERR -1
#define ERR_NOT_ENOUGH_POINTS_IN_FIRST_SET -2
#define ERR_NOT_ENOUGH_POINTS_IN_SECOND_SET -3
#define ERR_EQUIDISTANT_POINTS_NOT_FOUND -4
#define ERR_NO_EQUIDISTANT_POINTS_IN_FIRST_SET -5
#define ERR_NO_EQUIDISTANT_POINTS_IN_SECOND_SET -6

#define ERR_LINES_ARE_PARALLEL -10
#define ERR_LINES_ARE_THE_SAME -11
#define ERR_LINE_SEGMENTS_DO_NOT_INTERSECT -12

#endif // __ERROR_H__
